language: elixir

elixir:
  - 1.5
  - 1.6

script:
  - mix compile --warnings-as-errors
  - if [[ $(mix help format) ]]; then mix format --check-formatted; fi
  - mix credo
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
