language: elixir

otp_release:
  - 20.3
  - 21.0

elixir:
  - 1.6
  - 1.7

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted
  - mix credo
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
